
stages:
  - build
  # - deploy

build-job:
  image: node:18
  stage: build
  tags: 
    - docker
  artifacts:
    paths:
      - dist/*
    expire_in:
      1 week
  script:
    - echo "Compiling the code..."
    - npm ci
    - npm run build --prod
    - echo "Compile complete."
  rules:
    - if: "$CI_COMMIT_BRANCH == 'develop'"


# TODO: create (new) deploy job!