import { Workshop } from './workshop';

export const WORKSHOPS: Workshop[] = [
    { id: 11, title: 'Tasse', shortDescription: 'tasse beschreibung: Lorem ipsum dolor sit amet, consecteturadipiscing elit, sed do usmod tempor incididunt ut labore et', image:'', detailDescription: 'detail beschreibung über die tasse. dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ecommodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nullpariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.', isCollapsed:true},
    { id: 12, title: 'Teekanne', shortDescription: 'teekanne beschreibung: Lorem ipsum dolor sit amet, consecteturadipiscing elit, sed do usmod tempor incididunt ut labore et', image:'', detailDescription: 'detail beschreibung über die teekanne. dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ecommodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nullpariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.', isCollapsed:true},
    { id: 13, title: 'Teller', shortDescription: 'Teller beschreibung: Lorem ipsum dolor sit amet, consecteturadipiscing elit, sed do usmod tempor incididunt ut labore et', image:'', detailDescription: 'detail beschreibung über die Teller. dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ecommodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nullpariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.', isCollapsed:true},
    { id: 14, title: 'Messer', shortDescription: 'Messer beschreibung: Lorem ipsum dolor sit amet, consecteturadipiscing elit, sed do usmod tempor incididunt ut labore et', image:'', detailDescription: 'detail beschreibung über die Messer. dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ecommodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nullpariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.', isCollapsed:true},
    { id: 15, title: 'Gabel', shortDescription: 'Gabel beschreibung: Lorem ipsum dolor sit amet, consecteturadipiscing elit, sed do usmod tempor incididunt ut labore et', image:'', detailDescription: 'detail beschreibung über die Gabel. dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ecommodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nullpariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.', isCollapsed:true},
    { id: 16, title: 'Löffel', shortDescription: 'Löffel beschreibung: Lorem ipsum dolor sit amet, consecteturadipiscing elit, sed do usmod tempor incididunt ut labore et', image:'', detailDescription: 'detail beschreibung über die Löffel. dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ecommodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nullpariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.', isCollapsed:true},
  ];
  